# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
namespace: dev
namePrefix: dev-
resources:
  - namespace.yaml
  - ../../base
  - sealed-secrets.yaml
patches:
  - path: deployment.yaml
    target:
      kind: Deployment